[package]
name = "kakuro"
version = "0.1.0"
edition = "2018"

[profile.release]
debug = true

[dependencies]
chrono = "0.4"
itertools = "0.7.8"
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3.25"
num-bigint = "0.4"
